server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enable: true
      force : true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(??? ????), method(HTTP????)
    tags-sorter: alpha # ?? ?? ??
    path: /swagger-ui2.html # html ?? ?? ??
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation ??? ??
  paths-to-match:


